spring.application.name=HindiPdfReaderProject


# Database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/pdfreader
spring.datasource.username=postgres
spring.datasource.password=8008
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties
# or create, create-drop, none
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File upload settings
file.upload-dir=uploads

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
